{% set name = "cobra" %}
{% set version = "0.32.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cobra-{{ version }}.tar.gz
  sha256: f3e9b8284231fabf9b3cea2a4c407162f508d349695f268d00bec1d15169d73a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - appdirs
    - depinfo >=2.2
    - future
    - httpx >=0.24.0
    - importlib_resources
    - numpy >=1.13
    - optlang >=1.9.0
    - pandas >=1.0,<3.0
    - pydantic >=1.6
    - python >={{ python_min }}
    - python-libsbml >=5.19
    - rich >=8.0
    - ruamel.yaml >=0.16
    - swiglpk

test:
  imports:
    - cobra
    - cobra.flux_analysis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://opencobra.github.io/cobrapy
  summary: COBRApy is a package for constraints-based modeling of metabolic networks.
  license: LGPL-2.0-or-later OR GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  description: >
    Constraint-based reconstruction and analysis (COBRA) methods are widely used for genome-scale modeling of metabolic networks in both prokaryotes and eukaryotes. COBRApy is a constraint-based modeling package that is designed to accommodate the biological complexity of the next generation of COBRA models and provides
    access to commonly used COBRA methods, such as flux-balance analysis, flux variability analysis, and gene deletion analyses.
  doc_url: https://cobrapy.readthedocs.io
  dev_url: https://github.com/opencobra/cobrapy

extra:
  recipe-maintainers:
    - cdiener
    - Midnighter
